//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Client_WinPhone.ServFeed {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultat", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k))]
    public partial class Resultat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Client_WinPhone.ServFeed.Resultat.ErrorCode _errorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WinPhone.ServFeed.Resultat.ErrorCode _error {
            get {
                return this._errorField;
            }
            set {
                if ((this._errorField.Equals(value) != true)) {
                    this._errorField = value;
                    this.RaisePropertyChanged("_error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Resultat.ErrorCode", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
        public enum ErrorCode : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SUCCESS = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_NOT_FOUND = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_ALREADY_EXIST = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INFORMATION_REQUIRED = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NOT_LOGUED = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INTERNAL_ERROR = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NEED_PRIVILEGE = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ALREADY_LOGUED = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_CREATE_FEED = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_GET_FEED = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ITEM_NOT_FOUND = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PARAMETER_ERROR = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INVALID_PARAMETER = 12,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultatOfArrayOfChannelDataxs063O9k", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    public partial class ResultatOfArrayOfChannelDataxs063O9k : Client_WinPhone.ServFeed.Resultat {
        
        private System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.ServFeed.ChannelData> _valField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.ServFeed.ChannelData> _val {
            get {
                return this._valField;
            }
            set {
                if ((object.ReferenceEquals(this._valField, value) != true)) {
                    this._valField = value;
                    this.RaisePropertyChanged("_val");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultatOfArrayOfItemDataxs063O9k", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    public partial class ResultatOfArrayOfItemDataxs063O9k : Client_WinPhone.ServFeed.Resultat {
        
        private System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.ServFeed.ItemData> _valField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.ServFeed.ItemData> _val {
            get {
                return this._valField;
            }
            set {
                if ((object.ReferenceEquals(this._valField, value) != true)) {
                    this._valField = value;
                    this.RaisePropertyChanged("_val");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelData", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Services")]
    public partial class ChannelData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private int IdField;
        
        private string ImageField;
        
        private System.Nullable<System.DateTime> LastBuildDateField;
        
        private string LinkField;
        
        private System.Nullable<System.DateTime> PubDateField;
        
        private string TitleField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastBuildDate {
            get {
                return this.LastBuildDateField;
            }
            set {
                if ((this.LastBuildDateField.Equals(value) != true)) {
                    this.LastBuildDateField = value;
                    this.RaisePropertyChanged("LastBuildDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemData", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Services")]
    public partial class ItemData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AuthorField;
        
        private string CategoryField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string LinkField;
        
        private System.Nullable<System.DateTimeOffset> PubDateField;
        
        private bool ReadField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTimeOffset> PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Read {
            get {
                return this.ReadField;
            }
            set {
                if ((this.ReadField.Equals(value) != true)) {
                    this.ReadField = value;
                    this.RaisePropertyChanged("Read");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServFeed.Feed")]
    public interface Feed {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Feed/AddFeed", ReplyAction="http://tempuri.org/Feed/AddFeedResponse")]
        System.IAsyncResult BeginAddFeed(string session_key, System.Uri uri, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.ServFeed.Resultat EndAddFeed(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Feed/GetFeeds", ReplyAction="http://tempuri.org/Feed/GetFeedsResponse")]
        System.IAsyncResult BeginGetFeeds(string session_key, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k EndGetFeeds(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Feed/GetAllFeeds", ReplyAction="http://tempuri.org/Feed/GetAllFeedsResponse")]
        System.IAsyncResult BeginGetAllFeeds(System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k EndGetAllFeeds(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Feed/DeleteFeed", ReplyAction="http://tempuri.org/Feed/DeleteFeedResponse")]
        System.IAsyncResult BeginDeleteFeed(string session_key, Client_WinPhone.ServFeed.ChannelData chan, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.ServFeed.Resultat EndDeleteFeed(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Feed/GetItem", ReplyAction="http://tempuri.org/Feed/GetItemResponse")]
        System.IAsyncResult BeginGetItem(Client_WinPhone.ServFeed.ChannelData chan, string session_key, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k EndGetItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Feed/ReadItem", ReplyAction="http://tempuri.org/Feed/ReadItemResponse")]
        System.IAsyncResult BeginReadItem(string session_key, Client_WinPhone.ServFeed.ItemData item, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.ServFeed.Resultat EndReadItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Feed/Update", ReplyAction="http://tempuri.org/Feed/UpdateResponse")]
        System.IAsyncResult BeginUpdate(Client_WinPhone.ServFeed.ChannelData chan, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.ServFeed.Resultat EndUpdate(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FeedChannel : Client_WinPhone.ServFeed.Feed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.ServFeed.Resultat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.ServFeed.Resultat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.ServFeed.Resultat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.ServFeed.Resultat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReadItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.ServFeed.Resultat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.ServFeed.Resultat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.ServFeed.Resultat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.ServFeed.Resultat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedClient : System.ServiceModel.ClientBase<Client_WinPhone.ServFeed.Feed>, Client_WinPhone.ServFeed.Feed {
        
        private BeginOperationDelegate onBeginAddFeedDelegate;
        
        private EndOperationDelegate onEndAddFeedDelegate;
        
        private System.Threading.SendOrPostCallback onAddFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFeedsDelegate;
        
        private EndOperationDelegate onEndGetFeedsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFeedsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllFeedsDelegate;
        
        private EndOperationDelegate onEndGetAllFeedsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllFeedsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteFeedDelegate;
        
        private EndOperationDelegate onEndDeleteFeedDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetItemDelegate;
        
        private EndOperationDelegate onEndGetItemDelegate;
        
        private System.Threading.SendOrPostCallback onGetItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginReadItemDelegate;
        
        private EndOperationDelegate onEndReadItemDelegate;
        
        private System.Threading.SendOrPostCallback onReadItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDelegate;
        
        private EndOperationDelegate onEndUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public FeedClient() {
        }
        
        public FeedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AddFeedCompletedEventArgs> AddFeedCompleted;
        
        public event System.EventHandler<GetFeedsCompletedEventArgs> GetFeedsCompleted;
        
        public event System.EventHandler<GetAllFeedsCompletedEventArgs> GetAllFeedsCompleted;
        
        public event System.EventHandler<DeleteFeedCompletedEventArgs> DeleteFeedCompleted;
        
        public event System.EventHandler<GetItemCompletedEventArgs> GetItemCompleted;
        
        public event System.EventHandler<ReadItemCompletedEventArgs> ReadItemCompleted;
        
        public event System.EventHandler<UpdateCompletedEventArgs> UpdateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.ServFeed.Feed.BeginAddFeed(string session_key, System.Uri uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddFeed(session_key, uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.ServFeed.Resultat Client_WinPhone.ServFeed.Feed.EndAddFeed(System.IAsyncResult result) {
            return base.Channel.EndAddFeed(result);
        }
        
        private System.IAsyncResult OnBeginAddFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            System.Uri uri = ((System.Uri)(inValues[1]));
            return ((Client_WinPhone.ServFeed.Feed)(this)).BeginAddFeed(session_key, uri, callback, asyncState);
        }
        
        private object[] OnEndAddFeed(System.IAsyncResult result) {
            Client_WinPhone.ServFeed.Resultat retVal = ((Client_WinPhone.ServFeed.Feed)(this)).EndAddFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddFeedCompleted(object state) {
            if ((this.AddFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddFeedCompleted(this, new AddFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddFeedAsync(string session_key, System.Uri uri) {
            this.AddFeedAsync(session_key, uri, null);
        }
        
        public void AddFeedAsync(string session_key, System.Uri uri, object userState) {
            if ((this.onBeginAddFeedDelegate == null)) {
                this.onBeginAddFeedDelegate = new BeginOperationDelegate(this.OnBeginAddFeed);
            }
            if ((this.onEndAddFeedDelegate == null)) {
                this.onEndAddFeedDelegate = new EndOperationDelegate(this.OnEndAddFeed);
            }
            if ((this.onAddFeedCompletedDelegate == null)) {
                this.onAddFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddFeedCompleted);
            }
            base.InvokeAsync(this.onBeginAddFeedDelegate, new object[] {
                        session_key,
                        uri}, this.onEndAddFeedDelegate, this.onAddFeedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.ServFeed.Feed.BeginGetFeeds(string session_key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFeeds(session_key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k Client_WinPhone.ServFeed.Feed.EndGetFeeds(System.IAsyncResult result) {
            return base.Channel.EndGetFeeds(result);
        }
        
        private System.IAsyncResult OnBeginGetFeeds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            return ((Client_WinPhone.ServFeed.Feed)(this)).BeginGetFeeds(session_key, callback, asyncState);
        }
        
        private object[] OnEndGetFeeds(System.IAsyncResult result) {
            Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k retVal = ((Client_WinPhone.ServFeed.Feed)(this)).EndGetFeeds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFeedsCompleted(object state) {
            if ((this.GetFeedsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFeedsCompleted(this, new GetFeedsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFeedsAsync(string session_key) {
            this.GetFeedsAsync(session_key, null);
        }
        
        public void GetFeedsAsync(string session_key, object userState) {
            if ((this.onBeginGetFeedsDelegate == null)) {
                this.onBeginGetFeedsDelegate = new BeginOperationDelegate(this.OnBeginGetFeeds);
            }
            if ((this.onEndGetFeedsDelegate == null)) {
                this.onEndGetFeedsDelegate = new EndOperationDelegate(this.OnEndGetFeeds);
            }
            if ((this.onGetFeedsCompletedDelegate == null)) {
                this.onGetFeedsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFeedsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFeedsDelegate, new object[] {
                        session_key}, this.onEndGetFeedsDelegate, this.onGetFeedsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.ServFeed.Feed.BeginGetAllFeeds(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllFeeds(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k Client_WinPhone.ServFeed.Feed.EndGetAllFeeds(System.IAsyncResult result) {
            return base.Channel.EndGetAllFeeds(result);
        }
        
        private System.IAsyncResult OnBeginGetAllFeeds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Client_WinPhone.ServFeed.Feed)(this)).BeginGetAllFeeds(callback, asyncState);
        }
        
        private object[] OnEndGetAllFeeds(System.IAsyncResult result) {
            Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k retVal = ((Client_WinPhone.ServFeed.Feed)(this)).EndGetAllFeeds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllFeedsCompleted(object state) {
            if ((this.GetAllFeedsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllFeedsCompleted(this, new GetAllFeedsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllFeedsAsync() {
            this.GetAllFeedsAsync(null);
        }
        
        public void GetAllFeedsAsync(object userState) {
            if ((this.onBeginGetAllFeedsDelegate == null)) {
                this.onBeginGetAllFeedsDelegate = new BeginOperationDelegate(this.OnBeginGetAllFeeds);
            }
            if ((this.onEndGetAllFeedsDelegate == null)) {
                this.onEndGetAllFeedsDelegate = new EndOperationDelegate(this.OnEndGetAllFeeds);
            }
            if ((this.onGetAllFeedsCompletedDelegate == null)) {
                this.onGetAllFeedsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllFeedsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllFeedsDelegate, null, this.onEndGetAllFeedsDelegate, this.onGetAllFeedsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.ServFeed.Feed.BeginDeleteFeed(string session_key, Client_WinPhone.ServFeed.ChannelData chan, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteFeed(session_key, chan, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.ServFeed.Resultat Client_WinPhone.ServFeed.Feed.EndDeleteFeed(System.IAsyncResult result) {
            return base.Channel.EndDeleteFeed(result);
        }
        
        private System.IAsyncResult OnBeginDeleteFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            Client_WinPhone.ServFeed.ChannelData chan = ((Client_WinPhone.ServFeed.ChannelData)(inValues[1]));
            return ((Client_WinPhone.ServFeed.Feed)(this)).BeginDeleteFeed(session_key, chan, callback, asyncState);
        }
        
        private object[] OnEndDeleteFeed(System.IAsyncResult result) {
            Client_WinPhone.ServFeed.Resultat retVal = ((Client_WinPhone.ServFeed.Feed)(this)).EndDeleteFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteFeedCompleted(object state) {
            if ((this.DeleteFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteFeedCompleted(this, new DeleteFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteFeedAsync(string session_key, Client_WinPhone.ServFeed.ChannelData chan) {
            this.DeleteFeedAsync(session_key, chan, null);
        }
        
        public void DeleteFeedAsync(string session_key, Client_WinPhone.ServFeed.ChannelData chan, object userState) {
            if ((this.onBeginDeleteFeedDelegate == null)) {
                this.onBeginDeleteFeedDelegate = new BeginOperationDelegate(this.OnBeginDeleteFeed);
            }
            if ((this.onEndDeleteFeedDelegate == null)) {
                this.onEndDeleteFeedDelegate = new EndOperationDelegate(this.OnEndDeleteFeed);
            }
            if ((this.onDeleteFeedCompletedDelegate == null)) {
                this.onDeleteFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteFeedCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteFeedDelegate, new object[] {
                        session_key,
                        chan}, this.onEndDeleteFeedDelegate, this.onDeleteFeedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.ServFeed.Feed.BeginGetItem(Client_WinPhone.ServFeed.ChannelData chan, string session_key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetItem(chan, session_key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k Client_WinPhone.ServFeed.Feed.EndGetItem(System.IAsyncResult result) {
            return base.Channel.EndGetItem(result);
        }
        
        private System.IAsyncResult OnBeginGetItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Client_WinPhone.ServFeed.ChannelData chan = ((Client_WinPhone.ServFeed.ChannelData)(inValues[0]));
            string session_key = ((string)(inValues[1]));
            return ((Client_WinPhone.ServFeed.Feed)(this)).BeginGetItem(chan, session_key, callback, asyncState);
        }
        
        private object[] OnEndGetItem(System.IAsyncResult result) {
            Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k retVal = ((Client_WinPhone.ServFeed.Feed)(this)).EndGetItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetItemCompleted(object state) {
            if ((this.GetItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetItemCompleted(this, new GetItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetItemAsync(Client_WinPhone.ServFeed.ChannelData chan, string session_key) {
            this.GetItemAsync(chan, session_key, null);
        }
        
        public void GetItemAsync(Client_WinPhone.ServFeed.ChannelData chan, string session_key, object userState) {
            if ((this.onBeginGetItemDelegate == null)) {
                this.onBeginGetItemDelegate = new BeginOperationDelegate(this.OnBeginGetItem);
            }
            if ((this.onEndGetItemDelegate == null)) {
                this.onEndGetItemDelegate = new EndOperationDelegate(this.OnEndGetItem);
            }
            if ((this.onGetItemCompletedDelegate == null)) {
                this.onGetItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemCompleted);
            }
            base.InvokeAsync(this.onBeginGetItemDelegate, new object[] {
                        chan,
                        session_key}, this.onEndGetItemDelegate, this.onGetItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.ServFeed.Feed.BeginReadItem(string session_key, Client_WinPhone.ServFeed.ItemData item, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReadItem(session_key, item, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.ServFeed.Resultat Client_WinPhone.ServFeed.Feed.EndReadItem(System.IAsyncResult result) {
            return base.Channel.EndReadItem(result);
        }
        
        private System.IAsyncResult OnBeginReadItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            Client_WinPhone.ServFeed.ItemData item = ((Client_WinPhone.ServFeed.ItemData)(inValues[1]));
            return ((Client_WinPhone.ServFeed.Feed)(this)).BeginReadItem(session_key, item, callback, asyncState);
        }
        
        private object[] OnEndReadItem(System.IAsyncResult result) {
            Client_WinPhone.ServFeed.Resultat retVal = ((Client_WinPhone.ServFeed.Feed)(this)).EndReadItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReadItemCompleted(object state) {
            if ((this.ReadItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReadItemCompleted(this, new ReadItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReadItemAsync(string session_key, Client_WinPhone.ServFeed.ItemData item) {
            this.ReadItemAsync(session_key, item, null);
        }
        
        public void ReadItemAsync(string session_key, Client_WinPhone.ServFeed.ItemData item, object userState) {
            if ((this.onBeginReadItemDelegate == null)) {
                this.onBeginReadItemDelegate = new BeginOperationDelegate(this.OnBeginReadItem);
            }
            if ((this.onEndReadItemDelegate == null)) {
                this.onEndReadItemDelegate = new EndOperationDelegate(this.OnEndReadItem);
            }
            if ((this.onReadItemCompletedDelegate == null)) {
                this.onReadItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReadItemCompleted);
            }
            base.InvokeAsync(this.onBeginReadItemDelegate, new object[] {
                        session_key,
                        item}, this.onEndReadItemDelegate, this.onReadItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.ServFeed.Feed.BeginUpdate(Client_WinPhone.ServFeed.ChannelData chan, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate(chan, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.ServFeed.Resultat Client_WinPhone.ServFeed.Feed.EndUpdate(System.IAsyncResult result) {
            return base.Channel.EndUpdate(result);
        }
        
        private System.IAsyncResult OnBeginUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Client_WinPhone.ServFeed.ChannelData chan = ((Client_WinPhone.ServFeed.ChannelData)(inValues[0]));
            return ((Client_WinPhone.ServFeed.Feed)(this)).BeginUpdate(chan, callback, asyncState);
        }
        
        private object[] OnEndUpdate(System.IAsyncResult result) {
            Client_WinPhone.ServFeed.Resultat retVal = ((Client_WinPhone.ServFeed.Feed)(this)).EndUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateCompleted(object state) {
            if ((this.UpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateAsync(Client_WinPhone.ServFeed.ChannelData chan) {
            this.UpdateAsync(chan, null);
        }
        
        public void UpdateAsync(Client_WinPhone.ServFeed.ChannelData chan, object userState) {
            if ((this.onBeginUpdateDelegate == null)) {
                this.onBeginUpdateDelegate = new BeginOperationDelegate(this.OnBeginUpdate);
            }
            if ((this.onEndUpdateDelegate == null)) {
                this.onEndUpdateDelegate = new EndOperationDelegate(this.OnEndUpdate);
            }
            if ((this.onUpdateCompletedDelegate == null)) {
                this.onUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDelegate, new object[] {
                        chan}, this.onEndUpdateDelegate, this.onUpdateCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Client_WinPhone.ServFeed.Feed CreateChannel() {
            return new FeedClientChannel(this);
        }
        
        private class FeedClientChannel : ChannelBase<Client_WinPhone.ServFeed.Feed>, Client_WinPhone.ServFeed.Feed {
            
            public FeedClientChannel(System.ServiceModel.ClientBase<Client_WinPhone.ServFeed.Feed> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAddFeed(string session_key, System.Uri uri, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = session_key;
                _args[1] = uri;
                System.IAsyncResult _result = base.BeginInvoke("AddFeed", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.ServFeed.Resultat EndAddFeed(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.ServFeed.Resultat _result = ((Client_WinPhone.ServFeed.Resultat)(base.EndInvoke("AddFeed", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFeeds(string session_key, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = session_key;
                System.IAsyncResult _result = base.BeginInvoke("GetFeeds", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k EndGetFeeds(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k _result = ((Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k)(base.EndInvoke("GetFeeds", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllFeeds(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllFeeds", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k EndGetAllFeeds(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k _result = ((Client_WinPhone.ServFeed.ResultatOfArrayOfChannelDataxs063O9k)(base.EndInvoke("GetAllFeeds", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteFeed(string session_key, Client_WinPhone.ServFeed.ChannelData chan, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = session_key;
                _args[1] = chan;
                System.IAsyncResult _result = base.BeginInvoke("DeleteFeed", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.ServFeed.Resultat EndDeleteFeed(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.ServFeed.Resultat _result = ((Client_WinPhone.ServFeed.Resultat)(base.EndInvoke("DeleteFeed", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetItem(Client_WinPhone.ServFeed.ChannelData chan, string session_key, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = chan;
                _args[1] = session_key;
                System.IAsyncResult _result = base.BeginInvoke("GetItem", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k EndGetItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k _result = ((Client_WinPhone.ServFeed.ResultatOfArrayOfItemDataxs063O9k)(base.EndInvoke("GetItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginReadItem(string session_key, Client_WinPhone.ServFeed.ItemData item, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = session_key;
                _args[1] = item;
                System.IAsyncResult _result = base.BeginInvoke("ReadItem", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.ServFeed.Resultat EndReadItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.ServFeed.Resultat _result = ((Client_WinPhone.ServFeed.Resultat)(base.EndInvoke("ReadItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdate(Client_WinPhone.ServFeed.ChannelData chan, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = chan;
                System.IAsyncResult _result = base.BeginInvoke("Update", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.ServFeed.Resultat EndUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.ServFeed.Resultat _result = ((Client_WinPhone.ServFeed.Resultat)(base.EndInvoke("Update", _args, result)));
                return _result;
            }
        }
    }
}
