//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWPF.AccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultat", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWPF.AccountService.ResultatOfbooleanAccountDataGmrGjgq6))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientWPF.AccountService.ResultatOfstringAccountDataGmrGjgq6))]
    public partial class Resultat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.AccountService.Resultat.ErrorCode _errorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.AccountService.Resultat.ErrorCode _error {
            get {
                return this._errorField;
            }
            set {
                if ((this._errorField.Equals(value) != true)) {
                    this._errorField = value;
                    this.RaisePropertyChanged("_error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Resultat.ErrorCode", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
        public enum ErrorCode : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SUCCESS = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_NOT_FOUND = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_ALREADY_EXIST = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INFORMATION_REQUIRED = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NOT_LOGUED = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INTERNAL_ERROR = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NEED_PRIVILEGE = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ALREADY_LOGUED = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_CREATE_FEED = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_GET_FEED = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ITEM_NOT_FOUND = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PARAMETER_ERROR = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INVALID_PARAMETER = 12,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultatOfbooleanAccountDataGmrGjgq6", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    [System.SerializableAttribute()]
    public partial class ResultatOfbooleanAccountDataGmrGjgq6 : ClientWPF.AccountService.Resultat {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _val1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.AccountService.AccountData _val2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _val1 {
            get {
                return this._val1Field;
            }
            set {
                if ((this._val1Field.Equals(value) != true)) {
                    this._val1Field = value;
                    this.RaisePropertyChanged("_val1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.AccountService.AccountData _val2 {
            get {
                return this._val2Field;
            }
            set {
                if ((object.ReferenceEquals(this._val2Field, value) != true)) {
                    this._val2Field = value;
                    this.RaisePropertyChanged("_val2");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultatOfstringAccountDataGmrGjgq6", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    [System.SerializableAttribute()]
    public partial class ResultatOfstringAccountDataGmrGjgq6 : ClientWPF.AccountService.Resultat {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _val1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientWPF.AccountService.AccountData _val2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _val1 {
            get {
                return this._val1Field;
            }
            set {
                if ((object.ReferenceEquals(this._val1Field, value) != true)) {
                    this._val1Field = value;
                    this.RaisePropertyChanged("_val1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientWPF.AccountService.AccountData _val2 {
            get {
                return this._val2Field;
            }
            set {
                if ((object.ReferenceEquals(this._val2Field, value) != true)) {
                    this._val2Field = value;
                    this.RaisePropertyChanged("_val2");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountData", Namespace="http://schemas.datacontract.org/2004/07/ServerRss.Services")]
    [System.SerializableAttribute()]
    public partial class AccountData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.Account")]
    public interface Account {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account/Login", ReplyAction="http://tempuri.org/Account/LoginResponse")]
        ClientWPF.AccountService.ResultatOfstringAccountDataGmrGjgq6 Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/Login", ReplyAction="http://tempuri.org/Account/LoginResponse")]
        System.IAsyncResult BeginLogin(string email, string password, System.AsyncCallback callback, object asyncState);
        
        ClientWPF.AccountService.ResultatOfstringAccountDataGmrGjgq6 EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account/Register", ReplyAction="http://tempuri.org/Account/RegisterResponse")]
        ClientWPF.AccountService.Resultat Register(string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/Register", ReplyAction="http://tempuri.org/Account/RegisterResponse")]
        System.IAsyncResult BeginRegister(string email, string username, string password, System.AsyncCallback callback, object asyncState);
        
        ClientWPF.AccountService.Resultat EndRegister(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account/UpdateData", ReplyAction="http://tempuri.org/Account/UpdateDataResponse")]
        ClientWPF.AccountService.Resultat UpdateData(string session_key, [System.ServiceModel.MessageParameterAttribute(Name="updateData")] ClientWPF.AccountService.AccountData updateData1);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/UpdateData", ReplyAction="http://tempuri.org/Account/UpdateDataResponse")]
        System.IAsyncResult BeginUpdateData(string session_key, ClientWPF.AccountService.AccountData updateData, System.AsyncCallback callback, object asyncState);
        
        ClientWPF.AccountService.Resultat EndUpdateData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account/DeleteAccount", ReplyAction="http://tempuri.org/Account/DeleteAccountResponse")]
        ClientWPF.AccountService.Resultat DeleteAccount(string session_key);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/DeleteAccount", ReplyAction="http://tempuri.org/Account/DeleteAccountResponse")]
        System.IAsyncResult BeginDeleteAccount(string session_key, System.AsyncCallback callback, object asyncState);
        
        ClientWPF.AccountService.Resultat EndDeleteAccount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account/UpdatePassword", ReplyAction="http://tempuri.org/Account/UpdatePasswordResponse")]
        ClientWPF.AccountService.Resultat UpdatePassword(string session_key, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/UpdatePassword", ReplyAction="http://tempuri.org/Account/UpdatePasswordResponse")]
        System.IAsyncResult BeginUpdatePassword(string session_key, string password, System.AsyncCallback callback, object asyncState);
        
        ClientWPF.AccountService.Resultat EndUpdatePassword(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Account/IsConnected", ReplyAction="http://tempuri.org/Account/IsConnectedResponse")]
        ClientWPF.AccountService.ResultatOfbooleanAccountDataGmrGjgq6 IsConnected(string session_key);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/IsConnected", ReplyAction="http://tempuri.org/Account/IsConnectedResponse")]
        System.IAsyncResult BeginIsConnected(string session_key, System.AsyncCallback callback, object asyncState);
        
        ClientWPF.AccountService.ResultatOfbooleanAccountDataGmrGjgq6 EndIsConnected(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountChannel : ClientWPF.AccountService.Account, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClientWPF.AccountService.ResultatOfstringAccountDataGmrGjgq6 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClientWPF.AccountService.ResultatOfstringAccountDataGmrGjgq6)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClientWPF.AccountService.Resultat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClientWPF.AccountService.Resultat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClientWPF.AccountService.Resultat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClientWPF.AccountService.Resultat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClientWPF.AccountService.Resultat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClientWPF.AccountService.Resultat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdatePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdatePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClientWPF.AccountService.Resultat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClientWPF.AccountService.Resultat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsConnectedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IsConnectedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ClientWPF.AccountService.ResultatOfbooleanAccountDataGmrGjgq6 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ClientWPF.AccountService.ResultatOfbooleanAccountDataGmrGjgq6)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountClient : System.ServiceModel.ClientBase<ClientWPF.AccountService.Account>, ClientWPF.AccountService.Account {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegisterDelegate;
        
        private EndOperationDelegate onEndRegisterDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDataDelegate;
        
        private EndOperationDelegate onEndUpdateDataDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteAccountDelegate;
        
        private EndOperationDelegate onEndDeleteAccountDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteAccountCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdatePasswordDelegate;
        
        private EndOperationDelegate onEndUpdatePasswordDelegate;
        
        private System.Threading.SendOrPostCallback onUpdatePasswordCompletedDelegate;
        
        private BeginOperationDelegate onBeginIsConnectedDelegate;
        
        private EndOperationDelegate onEndIsConnectedDelegate;
        
        private System.Threading.SendOrPostCallback onIsConnectedCompletedDelegate;
        
        public AccountClient() {
        }
        
        public AccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<RegisterCompletedEventArgs> RegisterCompleted;
        
        public event System.EventHandler<UpdateDataCompletedEventArgs> UpdateDataCompleted;
        
        public event System.EventHandler<DeleteAccountCompletedEventArgs> DeleteAccountCompleted;
        
        public event System.EventHandler<UpdatePasswordCompletedEventArgs> UpdatePasswordCompleted;
        
        public event System.EventHandler<IsConnectedCompletedEventArgs> IsConnectedCompleted;
        
        public ClientWPF.AccountService.ResultatOfstringAccountDataGmrGjgq6 Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogin(string email, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(email, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ClientWPF.AccountService.ResultatOfstringAccountDataGmrGjgq6 EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginLogin(email, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            ClientWPF.AccountService.ResultatOfstringAccountDataGmrGjgq6 retVal = this.EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string email, string password) {
            this.LoginAsync(email, password, null);
        }
        
        public void LoginAsync(string email, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        email,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        public ClientWPF.AccountService.Resultat Register(string email, string username, string password) {
            return base.Channel.Register(email, username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRegister(string email, string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegister(email, username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ClientWPF.AccountService.Resultat EndRegister(System.IAsyncResult result) {
            return base.Channel.EndRegister(result);
        }
        
        private System.IAsyncResult OnBeginRegister(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            string username = ((string)(inValues[1]));
            string password = ((string)(inValues[2]));
            return this.BeginRegister(email, username, password, callback, asyncState);
        }
        
        private object[] OnEndRegister(System.IAsyncResult result) {
            ClientWPF.AccountService.Resultat retVal = this.EndRegister(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterCompleted(object state) {
            if ((this.RegisterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterAsync(string email, string username, string password) {
            this.RegisterAsync(email, username, password, null);
        }
        
        public void RegisterAsync(string email, string username, string password, object userState) {
            if ((this.onBeginRegisterDelegate == null)) {
                this.onBeginRegisterDelegate = new BeginOperationDelegate(this.OnBeginRegister);
            }
            if ((this.onEndRegisterDelegate == null)) {
                this.onEndRegisterDelegate = new EndOperationDelegate(this.OnEndRegister);
            }
            if ((this.onRegisterCompletedDelegate == null)) {
                this.onRegisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterDelegate, new object[] {
                        email,
                        username,
                        password}, this.onEndRegisterDelegate, this.onRegisterCompletedDelegate, userState);
        }
        
        public ClientWPF.AccountService.Resultat UpdateData(string session_key, ClientWPF.AccountService.AccountData updateData1) {
            return base.Channel.UpdateData(session_key, updateData1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdateData(string session_key, ClientWPF.AccountService.AccountData updateData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateData(session_key, updateData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ClientWPF.AccountService.Resultat EndUpdateData(System.IAsyncResult result) {
            return base.Channel.EndUpdateData(result);
        }
        
        private System.IAsyncResult OnBeginUpdateData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            ClientWPF.AccountService.AccountData updateData = ((ClientWPF.AccountService.AccountData)(inValues[1]));
            return this.BeginUpdateData(session_key, updateData, callback, asyncState);
        }
        
        private object[] OnEndUpdateData(System.IAsyncResult result) {
            ClientWPF.AccountService.Resultat retVal = this.EndUpdateData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateDataCompleted(object state) {
            if ((this.UpdateDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateDataCompleted(this, new UpdateDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateDataAsync(string session_key, ClientWPF.AccountService.AccountData updateData) {
            this.UpdateDataAsync(session_key, updateData, null);
        }
        
        public void UpdateDataAsync(string session_key, ClientWPF.AccountService.AccountData updateData, object userState) {
            if ((this.onBeginUpdateDataDelegate == null)) {
                this.onBeginUpdateDataDelegate = new BeginOperationDelegate(this.OnBeginUpdateData);
            }
            if ((this.onEndUpdateDataDelegate == null)) {
                this.onEndUpdateDataDelegate = new EndOperationDelegate(this.OnEndUpdateData);
            }
            if ((this.onUpdateDataCompletedDelegate == null)) {
                this.onUpdateDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateDataCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDataDelegate, new object[] {
                        session_key,
                        updateData}, this.onEndUpdateDataDelegate, this.onUpdateDataCompletedDelegate, userState);
        }
        
        public ClientWPF.AccountService.Resultat DeleteAccount(string session_key) {
            return base.Channel.DeleteAccount(session_key);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDeleteAccount(string session_key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteAccount(session_key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ClientWPF.AccountService.Resultat EndDeleteAccount(System.IAsyncResult result) {
            return base.Channel.EndDeleteAccount(result);
        }
        
        private System.IAsyncResult OnBeginDeleteAccount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            return this.BeginDeleteAccount(session_key, callback, asyncState);
        }
        
        private object[] OnEndDeleteAccount(System.IAsyncResult result) {
            ClientWPF.AccountService.Resultat retVal = this.EndDeleteAccount(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteAccountCompleted(object state) {
            if ((this.DeleteAccountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteAccountCompleted(this, new DeleteAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAccountAsync(string session_key) {
            this.DeleteAccountAsync(session_key, null);
        }
        
        public void DeleteAccountAsync(string session_key, object userState) {
            if ((this.onBeginDeleteAccountDelegate == null)) {
                this.onBeginDeleteAccountDelegate = new BeginOperationDelegate(this.OnBeginDeleteAccount);
            }
            if ((this.onEndDeleteAccountDelegate == null)) {
                this.onEndDeleteAccountDelegate = new EndOperationDelegate(this.OnEndDeleteAccount);
            }
            if ((this.onDeleteAccountCompletedDelegate == null)) {
                this.onDeleteAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteAccountCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteAccountDelegate, new object[] {
                        session_key}, this.onEndDeleteAccountDelegate, this.onDeleteAccountCompletedDelegate, userState);
        }
        
        public ClientWPF.AccountService.Resultat UpdatePassword(string session_key, string password) {
            return base.Channel.UpdatePassword(session_key, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdatePassword(string session_key, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdatePassword(session_key, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ClientWPF.AccountService.Resultat EndUpdatePassword(System.IAsyncResult result) {
            return base.Channel.EndUpdatePassword(result);
        }
        
        private System.IAsyncResult OnBeginUpdatePassword(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginUpdatePassword(session_key, password, callback, asyncState);
        }
        
        private object[] OnEndUpdatePassword(System.IAsyncResult result) {
            ClientWPF.AccountService.Resultat retVal = this.EndUpdatePassword(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdatePasswordCompleted(object state) {
            if ((this.UpdatePasswordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdatePasswordCompleted(this, new UpdatePasswordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdatePasswordAsync(string session_key, string password) {
            this.UpdatePasswordAsync(session_key, password, null);
        }
        
        public void UpdatePasswordAsync(string session_key, string password, object userState) {
            if ((this.onBeginUpdatePasswordDelegate == null)) {
                this.onBeginUpdatePasswordDelegate = new BeginOperationDelegate(this.OnBeginUpdatePassword);
            }
            if ((this.onEndUpdatePasswordDelegate == null)) {
                this.onEndUpdatePasswordDelegate = new EndOperationDelegate(this.OnEndUpdatePassword);
            }
            if ((this.onUpdatePasswordCompletedDelegate == null)) {
                this.onUpdatePasswordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatePasswordCompleted);
            }
            base.InvokeAsync(this.onBeginUpdatePasswordDelegate, new object[] {
                        session_key,
                        password}, this.onEndUpdatePasswordDelegate, this.onUpdatePasswordCompletedDelegate, userState);
        }
        
        public ClientWPF.AccountService.ResultatOfbooleanAccountDataGmrGjgq6 IsConnected(string session_key) {
            return base.Channel.IsConnected(session_key);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginIsConnected(string session_key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIsConnected(session_key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ClientWPF.AccountService.ResultatOfbooleanAccountDataGmrGjgq6 EndIsConnected(System.IAsyncResult result) {
            return base.Channel.EndIsConnected(result);
        }
        
        private System.IAsyncResult OnBeginIsConnected(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            return this.BeginIsConnected(session_key, callback, asyncState);
        }
        
        private object[] OnEndIsConnected(System.IAsyncResult result) {
            ClientWPF.AccountService.ResultatOfbooleanAccountDataGmrGjgq6 retVal = this.EndIsConnected(result);
            return new object[] {
                    retVal};
        }
        
        private void OnIsConnectedCompleted(object state) {
            if ((this.IsConnectedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IsConnectedCompleted(this, new IsConnectedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IsConnectedAsync(string session_key) {
            this.IsConnectedAsync(session_key, null);
        }
        
        public void IsConnectedAsync(string session_key, object userState) {
            if ((this.onBeginIsConnectedDelegate == null)) {
                this.onBeginIsConnectedDelegate = new BeginOperationDelegate(this.OnBeginIsConnected);
            }
            if ((this.onEndIsConnectedDelegate == null)) {
                this.onEndIsConnectedDelegate = new EndOperationDelegate(this.OnEndIsConnected);
            }
            if ((this.onIsConnectedCompletedDelegate == null)) {
                this.onIsConnectedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIsConnectedCompleted);
            }
            base.InvokeAsync(this.onBeginIsConnectedDelegate, new object[] {
                        session_key}, this.onEndIsConnectedDelegate, this.onIsConnectedCompletedDelegate, userState);
        }
    }
}
