//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.34003.
// 
#pragma warning disable 1591

namespace Client_outlook.ServFeed
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_Feed", Namespace = "http://tempuri.org/")]
    public partial class Feed : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback AddFeedOperationCompleted;

        private System.Threading.SendOrPostCallback GetFeedsOperationCompleted;

        private System.Threading.SendOrPostCallback GetAllFeedsOperationCompleted;

        private System.Threading.SendOrPostCallback DeleteFeedOperationCompleted;

        private System.Threading.SendOrPostCallback GetItemOperationCompleted;

        private System.Threading.SendOrPostCallback ReadItemOperationCompleted;

        private System.Threading.SendOrPostCallback UpdateOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public Feed()
        {
            this.Url = "http://localhost:61005/Services/Feed.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event AddFeedCompletedEventHandler AddFeedCompleted;

        /// <remarks/>
        public event GetFeedsCompletedEventHandler GetFeedsCompleted;

        /// <remarks/>
        public event GetAllFeedsCompletedEventHandler GetAllFeedsCompleted;

        /// <remarks/>
        public event DeleteFeedCompletedEventHandler DeleteFeedCompleted;

        /// <remarks/>
        public event GetItemCompletedEventHandler GetItemCompleted;

        /// <remarks/>
        public event ReadItemCompletedEventHandler ReadItemCompleted;

        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Feed/AddFeed", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Resultat AddFeed([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string session_key, [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI", IsNullable = true)] string uri)
        {
            object[] results = this.Invoke("AddFeed", new object[] {
                        session_key,
                        uri});
            return ((Resultat)(results[0]));
        }

        /// <remarks/>
        public void AddFeedAsync(string session_key, string uri)
        {
            this.AddFeedAsync(session_key, uri, null);
        }

        /// <remarks/>
        public void AddFeedAsync(string session_key, string uri, object userState)
        {
            if ((this.AddFeedOperationCompleted == null))
            {
                this.AddFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddFeedOperationCompleted);
            }
            this.InvokeAsync("AddFeed", new object[] {
                        session_key,
                        uri}, this.AddFeedOperationCompleted, userState);
        }

        private void OnAddFeedOperationCompleted(object arg)
        {
            if ((this.AddFeedCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddFeedCompleted(this, new AddFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Feed/GetFeeds", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ResultatOfArrayOfChannelDataxs063O9k GetFeeds([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string session_key)
        {
            object[] results = this.Invoke("GetFeeds", new object[] {
                        session_key});
            return ((ResultatOfArrayOfChannelDataxs063O9k)(results[0]));
        }

        /// <remarks/>
        public void GetFeedsAsync(string session_key)
        {
            this.GetFeedsAsync(session_key, null);
        }

        /// <remarks/>
        public void GetFeedsAsync(string session_key, object userState)
        {
            if ((this.GetFeedsOperationCompleted == null))
            {
                this.GetFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFeedsOperationCompleted);
            }
            this.InvokeAsync("GetFeeds", new object[] {
                        session_key}, this.GetFeedsOperationCompleted, userState);
        }

        private void OnGetFeedsOperationCompleted(object arg)
        {
            if ((this.GetFeedsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFeedsCompleted(this, new GetFeedsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Feed/GetAllFeeds", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ResultatOfArrayOfChannelDataxs063O9k GetAllFeeds()
        {
            object[] results = this.Invoke("GetAllFeeds", new object[0]);
            return ((ResultatOfArrayOfChannelDataxs063O9k)(results[0]));
        }

        /// <remarks/>
        public void GetAllFeedsAsync()
        {
            this.GetAllFeedsAsync(null);
        }

        /// <remarks/>
        public void GetAllFeedsAsync(object userState)
        {
            if ((this.GetAllFeedsOperationCompleted == null))
            {
                this.GetAllFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllFeedsOperationCompleted);
            }
            this.InvokeAsync("GetAllFeeds", new object[0], this.GetAllFeedsOperationCompleted, userState);
        }

        private void OnGetAllFeedsOperationCompleted(object arg)
        {
            if ((this.GetAllFeedsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllFeedsCompleted(this, new GetAllFeedsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Feed/DeleteFeed", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Resultat DeleteFeed([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string session_key, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] ChannelData chan)
        {
            object[] results = this.Invoke("DeleteFeed", new object[] {
                        session_key,
                        chan});
            return ((Resultat)(results[0]));
        }

        /// <remarks/>
        public void DeleteFeedAsync(string session_key, ChannelData chan)
        {
            this.DeleteFeedAsync(session_key, chan, null);
        }

        /// <remarks/>
        public void DeleteFeedAsync(string session_key, ChannelData chan, object userState)
        {
            if ((this.DeleteFeedOperationCompleted == null))
            {
                this.DeleteFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFeedOperationCompleted);
            }
            this.InvokeAsync("DeleteFeed", new object[] {
                        session_key,
                        chan}, this.DeleteFeedOperationCompleted, userState);
        }

        private void OnDeleteFeedOperationCompleted(object arg)
        {
            if ((this.DeleteFeedCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFeedCompleted(this, new DeleteFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Feed/GetItem", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ResultatOfArrayOfItemDataxs063O9k GetItem([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] ChannelData chan, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string session_key)
        {
            object[] results = this.Invoke("GetItem", new object[] {
                        chan,
                        session_key});
            return ((ResultatOfArrayOfItemDataxs063O9k)(results[0]));
        }

        /// <remarks/>
        public void GetItemAsync(ChannelData chan, string session_key)
        {
            this.GetItemAsync(chan, session_key, null);
        }

        /// <remarks/>
        public void GetItemAsync(ChannelData chan, string session_key, object userState)
        {
            if ((this.GetItemOperationCompleted == null))
            {
                this.GetItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemOperationCompleted);
            }
            this.InvokeAsync("GetItem", new object[] {
                        chan,
                        session_key}, this.GetItemOperationCompleted, userState);
        }

        private void OnGetItemOperationCompleted(object arg)
        {
            if ((this.GetItemCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemCompleted(this, new GetItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Feed/ReadItem", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Resultat ReadItem([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string session_key, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] ItemData item)
        {
            object[] results = this.Invoke("ReadItem", new object[] {
                        session_key,
                        item});
            return ((Resultat)(results[0]));
        }

        /// <remarks/>
        public void ReadItemAsync(string session_key, ItemData item)
        {
            this.ReadItemAsync(session_key, item, null);
        }

        /// <remarks/>
        public void ReadItemAsync(string session_key, ItemData item, object userState)
        {
            if ((this.ReadItemOperationCompleted == null))
            {
                this.ReadItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadItemOperationCompleted);
            }
            this.InvokeAsync("ReadItem", new object[] {
                        session_key,
                        item}, this.ReadItemOperationCompleted, userState);
        }

        private void OnReadItemOperationCompleted(object arg)
        {
            if ((this.ReadItemCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadItemCompleted(this, new ReadItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Feed/Update", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Resultat Update([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] ChannelData chan)
        {
            object[] results = this.Invoke("Update", new object[] {
                        chan});
            return ((Resultat)(results[0]));
        }

        /// <remarks/>
        public void UpdateAsync(ChannelData chan)
        {
            this.UpdateAsync(chan, null);
        }

        /// <remarks/>
        public void UpdateAsync(ChannelData chan, object userState)
        {
            if ((this.UpdateOperationCompleted == null))
            {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        chan}, this.UpdateOperationCompleted, userState);
        }

        private void OnUpdateOperationCompleted(object arg)
        {
            if ((this.UpdateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultatOfArrayOfItemDataxs063O9k))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultatOfArrayOfChannelDataxs063O9k))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    public partial class Resultat
    {

        private ResultatErrorCode _errorField;

        private bool _errorFieldSpecified;

        /// <remarks/>
        public ResultatErrorCode _error
        {
            get
            {
                return this._errorField;
            }
            set
            {
                this._errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _errorSpecified
        {
            get
            {
                return this._errorFieldSpecified;
            }
            set
            {
                this._errorFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Resultat.ErrorCode", Namespace = "http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    public enum ResultatErrorCode
    {

        /// <remarks/>
        SUCCESS,

        /// <remarks/>
        USER_NOT_FOUND,

        /// <remarks/>
        USER_ALREADY_EXIST,

        /// <remarks/>
        INFORMATION_REQUIRED,

        /// <remarks/>
        NOT_LOGUED,

        /// <remarks/>
        INTERNAL_ERROR,

        /// <remarks/>
        NEED_PRIVILEGE,

        /// <remarks/>
        ALREADY_LOGUED,

        /// <remarks/>
        CANNOT_CREATE_FEED,

        /// <remarks/>
        CANNOT_GET_FEED,

        /// <remarks/>
        ITEM_NOT_FOUND,

        /// <remarks/>
        PARAMETER_ERROR,

        /// <remarks/>
        INVALID_PARAMETER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/System")]
    public partial class DateTimeOffset
    {

        private System.DateTime dateTimeField;

        private short offsetMinutesField;

        /// <remarks/>
        public System.DateTime DateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }

        /// <remarks/>
        public short OffsetMinutes
        {
            get
            {
                return this.offsetMinutesField;
            }
            set
            {
                this.offsetMinutesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerRss.Services")]
    public partial class ItemData
    {

        private string authorField;

        private string categoryField;

        private string descriptionField;

        private int idField;

        private bool idFieldSpecified;

        private string linkField;

        private DateTimeOffset pubDateField;

        private bool readField;

        private bool readFieldSpecified;

        private string titleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public DateTimeOffset PubDate
        {
            get
            {
                return this.pubDateField;
            }
            set
            {
                this.pubDateField = value;
            }
        }

        /// <remarks/>
        public bool Read
        {
            get
            {
                return this.readField;
            }
            set
            {
                this.readField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadSpecified
        {
            get
            {
                return this.readFieldSpecified;
            }
            set
            {
                this.readFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerRss.Services")]
    public partial class ChannelData
    {

        private string descriptionField;

        private int idField;

        private bool idFieldSpecified;

        private string imageField;

        private System.Nullable<System.DateTime> lastBuildDateField;

        private bool lastBuildDateFieldSpecified;

        private string linkField;

        private System.Nullable<System.DateTime> pubDateField;

        private bool pubDateFieldSpecified;

        private string titleField;

        private string urlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> LastBuildDate
        {
            get
            {
                return this.lastBuildDateField;
            }
            set
            {
                this.lastBuildDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastBuildDateSpecified
        {
            get
            {
                return this.lastBuildDateFieldSpecified;
            }
            set
            {
                this.lastBuildDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> PubDate
        {
            get
            {
                return this.pubDateField;
            }
            set
            {
                this.pubDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PubDateSpecified
        {
            get
            {
                return this.pubDateFieldSpecified;
            }
            set
            {
                this.pubDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    public partial class ResultatOfArrayOfItemDataxs063O9k : Resultat
    {

        private ItemData[] _valField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerRss.Services")]
        public ItemData[] _val
        {
            get
            {
                return this._valField;
            }
            set
            {
                this._valField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerRss.Tools")]
    public partial class ResultatOfArrayOfChannelDataxs063O9k : Resultat
    {

        private ChannelData[] _valField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "http://schemas.datacontract.org/2004/07/ServerRss.Services")]
        public ChannelData[] _val
        {
            get
            {
                return this._valField;
            }
            set
            {
                this._valField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void AddFeedCompletedEventHandler(object sender, AddFeedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AddFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Resultat Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Resultat)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetFeedsCompletedEventHandler(object sender, GetFeedsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ResultatOfArrayOfChannelDataxs063O9k Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ResultatOfArrayOfChannelDataxs063O9k)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetAllFeedsCompletedEventHandler(object sender, GetAllFeedsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAllFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ResultatOfArrayOfChannelDataxs063O9k Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ResultatOfArrayOfChannelDataxs063O9k)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void DeleteFeedCompletedEventHandler(object sender, DeleteFeedCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DeleteFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Resultat Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Resultat)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetItemCompletedEventHandler(object sender, GetItemCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ResultatOfArrayOfItemDataxs063O9k Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ResultatOfArrayOfItemDataxs063O9k)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ReadItemCompletedEventHandler(object sender, ReadItemCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ReadItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Resultat Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Resultat)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Resultat Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Resultat)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591